{
 "title": "UTAC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chemical Tin Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_prediction_ct3hours{}", "legendFormat": "3 hours ahead" },
    { "expr": "request_prediction_ct24hours{}", "legendFormat": "24 hours ahead" },
    {
     "expr": "request_prediction_ct168hours{}",
     "legendFormat": "168 hours ahead"
    }
   ]
  },
  {
   "title": "Solder Thickness Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "request_prediction_st3hours{}", "legendFormat": "3 hours ahead" },
    { "expr": "request_prediction_st24hours{}", "legendFormat": "24 hours ahead" },
    {
     "expr": "request_prediction_st168hours{}",
     "legendFormat": "168 hours ahead"
    }
   ]
  },
  {
   "title": "Alarm Prediction (1 hour ahead)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "request_no_alarm_prediction", "legendFormat": "No Alarm" },
    { "expr": "request_inload_prob_prediction", "legendFormat": "INLOAD PROB***" },
    { "expr": "request_others_prediction", "legendFormat": "Other" },
    {
     "expr": "request_others_machine_problem_prediction",
     "legendFormat": "Others Machine Problem***"
    },
    {
     "expr": "request_rectifiers_problem_prediction",
     "legendFormat": "Rectifiers problem***"
    },
    { "expr": "request_unload_prob_prediction", "legendFormat": "UNLOAD PROB***" }
   ]
  },
  {
   "title": "Defect Prediction (1 hour ahead)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "request_no_defect_prediction", "legendFormat": "No Defect" },
    {
     "expr": "request_copper_residue_gu_prediction",
     "legendFormat": "COPPER RESIDUE_GU"
    },
    {
     "expr": "request_exposed_foreign_material_dot_gt_prediction",
     "legendFormat": "EXPOSED FOREIGN MATERIAL (DOT)_GT"
    },
    {
     "expr": "request_flash_resin_bleed_sm_prediction",
     "legendFormat": "FLASH / RESIN BLEED_SM"
    },
    {
     "expr": "request_others_defect_prediction",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{endpoint=~\"/predict/ct/hours168|/predict/ct/hours24|/predict/ct/hours3|/predict/st/hours168|/predict/st/hours24|/predict/st/hours3|/predict/alarm/hour1|/predict/defect/hour1\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds{endpoint=~\"/predict/ct/hours168|/predict/ct/hours24|/predict/ct/hours3|/predict/st/hours168|/predict/st/hours24|/predict/st/hours3|/predict/alarm/hour1|/predict/defect/hour1\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Model Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_version_ct3hours{}", "legendFormat": "ct3hours" },
    { "expr": "model_version_ct24hours{}", "legendFormat": "ct24hours" },
    { "expr": "model_version_ct168hours{}", "legendFormat": "ct168hours" },
    { "expr": "model_version_st3hours{}", "legendFormat": "st3hours" },
    { "expr": "model_version_st24hours{}", "legendFormat": "st24hours" },
    { "expr": "model_version_st168hours{}", "legendFormat": "st168hours" },
    { "expr": "model_version_alarm_binary{}", "legendFormat": "binary_alarm" },
    {
     "expr": "model_version_alarm_multiclass{}",
     "legendFormat": "multiclass_alarm"
    },
    { "expr": "model_version_defect_binary{}", "legendFormat": "binary_defect" },
    {
     "expr": "model_version_defect_multiclass{}",
     "legendFormat": "multiclass_defect"
    }
   ]
  },
  {
   "title": "Model Retrain Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_retrain_ct3hours_total{}", "legendFormat": "ct3hours" },
    {
     "expr": "model_retrain_ct24hours_total{}",
     "legendFormat": "ct24hours"
    },
    {
     "expr": "model_retrain_ct168hours_total{}",
     "legendFormat": "ct168hours"
    },
    { "expr": "model_retrain_st3hours_total{}", "legendFormat": "st3hours" },
    {
     "expr": "model_retrain_st24hours_total{}",
     "legendFormat": "st24hours"
    },
    {
     "expr": "model_retrain_st168hours_total{}",
     "legendFormat": "st168hours"
    },
    {
     "expr": "model_retrain_alarm_binary_total{}",
     "legendFormat": "binary_alarm"
    },
    {
     "expr": "model_retrain_alarm_multiclass_total{}",
     "legendFormat": "multiclass_alarm"
    },
    {
     "expr": "model_retrain_defect_binary_total{}",
     "legendFormat": "binary_defect"
    },
    {
     "expr": "model_retrain_defect_multiclass_total{}",
     "legendFormat": "multiclass_defect"
    }
   ]
  },
  {
   "title": "Model Retraining Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_status_ct3hours{model_status_ct3hours=\"retraining\"}",
     "legendFormat": "ct3hours"
    },
    {
     "expr": "model_status_ct24hours{model_status_ct24hours=\"retraining\"}",
     "legendFormat": "ct24hours"
    },
    {
     "expr": "model_status_ct168hours{model_status_ct168hours=\"retraining\"}",
     "legendFormat": "ct168hours"
    },
    {
     "expr": "model_status_st3hours{model_status_st3hours=\"retraining\"}",
     "legendFormat": "st3hours"
    },
    {
     "expr": "model_status_st24hours{model_status_st24hours=\"retraining\"}",
     "legendFormat": "st24hours"
    },
    {
     "expr": "model_status_st168hours{model_status_st168hours=\"retraining\"}",
     "legendFormat": "st168hours"
    },
    {
     "expr": "model_status_alarm_binary{model_status_alarm_binary=\"retraining\"}",
     "legendFormat": "binary_alarm"
    },
    {
     "expr": "model_status_alarm_multiclass{model_status_alarm_multiclass=\"retraining\"}",
     "legendFormat": "multiclass_alarm"
    },
    {
     "expr": "model_status_defect_binary{model_status_defect_binary=\"retraining\"}",
     "legendFormat": "binary_defect"
    },
    {
     "expr": "model_status_defect_multiclass{model_status_defect_multiclass=\"retraining\"}",
     "legendFormat": "multiclass_defect"
    }
   ]
  }
 ]
}